create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 24),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.puzzle_bank (
  id bigint generated by default as identity primary key,
  puzzle_key text not null unique,
  numbers int[] not null check (array_length(numbers, 1) = 4),
  created_at timestamptz not null default now()
);

create table if not exists public.daily_events (
  id uuid primary key default gen_random_uuid(),
  event_date date not null unique,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.event_puzzles (
  event_id uuid not null references public.daily_events(id) on delete cascade,
  puzzle_index int not null check (puzzle_index between 1 and 10),
  puzzle_id bigint not null references public.puzzle_bank(id),
  primary key (event_id, puzzle_index),
  unique (event_id, puzzle_id)
);

create table if not exists public.runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references public.daily_events(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  score_ms bigint,
  run_status text not null default 'active' check (run_status in ('active', 'completed')),
  unique (user_id, event_id),
  check (score_ms is null or score_ms >= 0),
  check (
    (run_status = 'active' and completed_at is null and score_ms is null)
    or (run_status = 'completed' and completed_at is not null and score_ms is not null)
  )
);

create table if not exists public.run_solutions (
  run_id uuid not null references public.runs(id) on delete cascade,
  puzzle_index int not null check (puzzle_index between 1 and 10),
  steps jsonb not null,
  submitted_at timestamptz not null default now(),
  primary key (run_id, puzzle_index)
);

alter table public.profiles enable row level security;
alter table public.puzzle_bank enable row level security;
alter table public.daily_events enable row level security;
alter table public.event_puzzles enable row level security;
alter table public.runs enable row level security;
alter table public.run_solutions enable row level security;

drop policy if exists "profiles are visible" on public.profiles;
create policy "profiles are visible"
on public.profiles for select
using (true);

drop policy if exists "profiles insert own row" on public.profiles;
create policy "profiles insert own row"
on public.profiles for insert
with check ((select auth.uid()) = id);

drop policy if exists "profiles update own row" on public.profiles;
create policy "profiles update own row"
on public.profiles for update
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "runs read own row" on public.runs;
create policy "runs read own row"
on public.runs for select
using ((select auth.uid()) = user_id);

drop policy if exists "solutions read own run" on public.run_solutions;
create policy "solutions read own run"
on public.run_solutions for select
using (
  exists (
    select 1
    from public.runs r
    where r.id = run_solutions.run_id
      and r.user_id = (select auth.uid())
  )
);

insert into public.puzzle_bank (puzzle_key, numbers)
values
  ('3-8-12-13', array[3, 8, 12, 13]),
  ('2-3-7-8', array[2, 3, 7, 8]),
  ('1-4-8-11', array[1, 4, 8, 11]),
  ('2-3-5-12', array[2, 3, 5, 12]),
  ('1-2-8-8', array[1, 2, 8, 8]),
  ('2-7-7-10', array[2, 7, 7, 10]),
  ('1-1-3-10', array[1, 1, 3, 10]),
  ('1-1-4-7', array[1, 1, 4, 7]),
  ('2-3-3-6', array[2, 3, 3, 6]),
  ('1-5-12-12', array[1, 5, 12, 12]),
  ('6-11-12-13', array[6, 11, 12, 13]),
  ('3-4-8-12', array[3, 4, 8, 12]),
  ('4-6-9-12', array[4, 6, 9, 12]),
  ('1-2-8-10', array[1, 2, 8, 10]),
  ('10-10-11-13', array[10, 10, 11, 13]),
  ('6-8-9-11', array[6, 8, 9, 11]),
  ('5-6-9-13', array[5, 6, 9, 13]),
  ('1-1-2-13', array[1, 1, 2, 13]),
  ('1-4-5-9', array[1, 4, 5, 9]),
  ('1-2-3-5', array[1, 2, 3, 5]),
  ('2-6-6-8', array[2, 6, 6, 8]),
  ('6-9-12-13', array[6, 9, 12, 13]),
  ('2-2-5-8', array[2, 2, 5, 8]),
  ('3-7-8-13', array[3, 7, 8, 13]),
  ('1-2-4-10', array[1, 2, 4, 10]),
  ('5-6-11-11', array[5, 6, 11, 11]),
  ('4-6-6-7', array[4, 6, 6, 7]),
  ('1-4-4-12', array[1, 4, 4, 12]),
  ('1-2-9-13', array[1, 2, 9, 13]),
  ('1-5-8-10', array[1, 5, 8, 10]),
  ('2-3-4-13', array[2, 3, 4, 13]),
  ('9-12-12-12', array[9, 12, 12, 12]),
  ('1-1-1-8', array[1, 1, 1, 8]),
  ('4-5-6-13', array[4, 5, 6, 13]),
  ('1-4-5-13', array[1, 4, 5, 13]),
  ('4-4-12-12', array[4, 4, 12, 12]),
  ('4-10-12-12', array[4, 10, 12, 12]),
  ('6-8-9-12', array[6, 8, 9, 12]),
  ('1-7-7-10', array[1, 7, 7, 10]),
  ('3-5-12-13', array[3, 5, 12, 13]),
  ('1-7-9-9', array[1, 7, 9, 9]),
  ('2-6-7-13', array[2, 6, 7, 13]),
  ('1-5-6-6', array[1, 5, 6, 6]),
  ('1-2-5-13', array[1, 2, 5, 13]),
  ('1-6-12-12', array[1, 6, 12, 12]),
  ('3-5-10-12', array[3, 5, 10, 12]),
  ('1-5-7-13', array[1, 5, 7, 13]),
  ('4-8-8-8', array[4, 8, 8, 8]),
  ('8-8-8-13', array[8, 8, 8, 13]),
  ('6-9-11-13', array[6, 9, 11, 13]),
  ('1-4-6-11', array[1, 4, 6, 11]),
  ('3-4-4-8', array[3, 4, 4, 8]),
  ('3-4-12-13', array[3, 4, 12, 13]),
  ('2-8-10-13', array[2, 8, 10, 13]),
  ('4-5-10-10', array[4, 5, 10, 10]),
  ('3-8-8-9', array[3, 8, 8, 9]),
  ('6-7-9-9', array[6, 7, 9, 9]),
  ('3-5-5-11', array[3, 5, 5, 11]),
  ('1-3-9-9', array[1, 3, 9, 9]),
  ('3-7-9-13', array[3, 7, 9, 13]),
  ('4-8-10-11', array[4, 8, 10, 11]),
  ('5-5-7-11', array[5, 5, 7, 11]),
  ('3-5-6-10', array[3, 5, 6, 10]),
  ('4-4-5-10', array[4, 4, 5, 10]),
  ('1-5-6-9', array[1, 5, 6, 9]),
  ('2-2-8-8', array[2, 2, 8, 8]),
  ('5-5-12-12', array[5, 5, 12, 12]),
  ('2-5-5-13', array[2, 5, 5, 13]),
  ('9-9-11-13', array[9, 9, 11, 13]),
  ('3-3-6-7', array[3, 3, 6, 7]),
  ('6-6-8-9', array[6, 6, 8, 9]),
  ('3-4-6-8', array[3, 4, 6, 8]),
  ('6-8-11-13', array[6, 8, 11, 13]),
  ('1-6-7-9', array[1, 6, 7, 9]),
  ('2-6-8-9', array[2, 6, 8, 9]),
  ('3-9-11-12', array[3, 9, 11, 12]),
  ('5-7-8-10', array[5, 7, 8, 10]),
  ('4-4-11-12', array[4, 4, 11, 12]),
  ('3-3-4-5', array[3, 3, 4, 5]),
  ('6-6-10-13', array[6, 6, 10, 13]),
  ('4-9-11-12', array[4, 9, 11, 12]),
  ('2-7-8-11', array[2, 7, 8, 11]),
  ('3-8-13-13', array[3, 8, 13, 13]),
  ('1-5-6-13', array[1, 5, 6, 13]),
  ('3-6-9-12', array[3, 6, 9, 12]),
  ('1-3-3-11', array[1, 3, 3, 11]),
  ('3-9-10-11', array[3, 9, 10, 11]),
  ('2-6-7-8', array[2, 6, 7, 8]),
  ('2-4-10-11', array[2, 4, 10, 11]),
  ('1-2-4-5', array[1, 2, 4, 5]),
  ('2-4-9-12', array[2, 4, 9, 12]),
  ('4-6-7-12', array[4, 6, 7, 12]),
  ('1-1-6-12', array[1, 1, 6, 12]),
  ('1-2-2-6', array[1, 2, 2, 6]),
  ('5-5-11-12', array[5, 5, 11, 12]),
  ('2-2-6-10', array[2, 2, 6, 10]),
  ('4-7-8-13', array[4, 7, 8, 13]),
  ('2-6-10-12', array[2, 6, 10, 12]),
  ('7-8-11-12', array[7, 8, 11, 12]),
  ('1-1-1-11', array[1, 1, 1, 11]),
  ('1-4-4-10', array[1, 4, 4, 10]),
  ('2-12-12-13', array[2, 12, 12, 13]),
  ('1-4-5-5', array[1, 4, 5, 5]),
  ('4-7-9-12', array[4, 7, 9, 12]),
  ('5-10-12-13', array[5, 10, 12, 13]),
  ('4-9-9-12', array[4, 9, 9, 12]),
  ('2-5-11-12', array[2, 5, 11, 12]),
  ('5-5-6-6', array[5, 5, 6, 6]),
  ('4-5-7-12', array[4, 5, 7, 12]),
  ('3-6-7-7', array[3, 6, 7, 7]),
  ('1-4-10-10', array[1, 4, 10, 10]),
  ('4-4-12-13', array[4, 4, 12, 13]),
  ('6-6-7-11', array[6, 6, 7, 11]),
  ('1-3-9-11', array[1, 3, 9, 11]),
  ('3-3-7-8', array[3, 3, 7, 8]),
  ('10-10-10-13', array[10, 10, 10, 13]),
  ('6-8-12-12', array[6, 8, 12, 12]),
  ('2-5-8-11', array[2, 5, 8, 11]),
  ('1-1-2-10', array[1, 1, 2, 10]),
  ('1-3-5-12', array[1, 3, 5, 12])
on conflict (puzzle_key) do nothing;

create or replace function public.today_in_shanghai()
returns date
language sql
stable
as $$
  select (now() at time zone 'Asia/Shanghai')::date;
$$;

create or replace function public.gcd_bigint(a bigint, b bigint)
returns bigint
language plpgsql
immutable
strict
set search_path = public
as $$
declare
  x bigint := abs(a);
  y bigint := abs(b);
  t bigint;
begin
  while y <> 0 loop
    t := x % y;
    x := y;
    y := t;
  end loop;

  return greatest(x, 1);
end;
$$;

create or replace function public.validate_24_solution(
  p_numbers int[],
  p_steps jsonb
)
returns boolean
language plpgsql
immutable
set search_path = public
as $$
declare
  v_ids text[] := array['n0', 'n1', 'n2', 'n3'];
  v_nums bigint[] := array[p_numbers[1]::bigint, p_numbers[2]::bigint, p_numbers[3]::bigint, p_numbers[4]::bigint];
  v_dens bigint[] := array[1::bigint, 1::bigint, 1::bigint, 1::bigint];
  v_new_ids text[];
  v_new_nums bigint[];
  v_new_dens bigint[];
  v_i int;
  v_j int;
  v_step jsonb;
  v_left_id text;
  v_right_id text;
  v_result_id text;
  v_operator_code text;
  v_left_pos int;
  v_right_pos int;
  v_num bigint;
  v_den bigint;
  v_gcd bigint;
begin
  if p_numbers is null
    or array_length(p_numbers, 1) <> 4
    or p_steps is null
    or jsonb_typeof(p_steps) <> 'array'
    or jsonb_array_length(p_steps) <> 3
  then
    return false;
  end if;

  for v_i in 0..2 loop
    v_step := p_steps -> v_i;

    if jsonb_typeof(v_step) <> 'object' then
      return false;
    end if;

    v_left_id := v_step ->> 'left_id';
    v_right_id := v_step ->> 'right_id';
    v_operator_code := v_step ->> 'operator_code';
    v_result_id := v_step ->> 'result_id';

    if v_result_id <> ('r' || v_i::text) then
      return false;
    end if;

    v_left_pos := array_position(v_ids, v_left_id);
    v_right_pos := array_position(v_ids, v_right_id);

    if v_left_pos is null or v_right_pos is null or v_left_pos = v_right_pos then
      return false;
    end if;

    case v_operator_code
      when '+' then
        v_num := v_nums[v_left_pos] * v_dens[v_right_pos]
          + v_nums[v_right_pos] * v_dens[v_left_pos];
        v_den := v_dens[v_left_pos] * v_dens[v_right_pos];
      when '-' then
        v_num := v_nums[v_left_pos] * v_dens[v_right_pos]
          - v_nums[v_right_pos] * v_dens[v_left_pos];
        v_den := v_dens[v_left_pos] * v_dens[v_right_pos];
      when '*' then
        v_num := v_nums[v_left_pos] * v_nums[v_right_pos];
        v_den := v_dens[v_left_pos] * v_dens[v_right_pos];
      when '/' then
        if v_nums[v_right_pos] = 0 then
          return false;
        end if;
        v_num := v_nums[v_left_pos] * v_dens[v_right_pos];
        v_den := v_dens[v_left_pos] * v_nums[v_right_pos];
      else
        return false;
    end case;

    if v_den = 0 then
      return false;
    end if;

    if v_den < 0 then
      v_num := -v_num;
      v_den := -v_den;
    end if;

    v_gcd := public.gcd_bigint(v_num, v_den);
    v_num := v_num / v_gcd;
    v_den := v_den / v_gcd;

    v_new_ids := array[]::text[];
    v_new_nums := array[]::bigint[];
    v_new_dens := array[]::bigint[];

    for v_j in 1..array_length(v_ids, 1) loop
      if v_j <> v_left_pos and v_j <> v_right_pos then
        v_new_ids := array_append(v_new_ids, v_ids[v_j]);
        v_new_nums := array_append(v_new_nums, v_nums[v_j]);
        v_new_dens := array_append(v_new_dens, v_dens[v_j]);
      end if;
    end loop;

    v_ids := array_append(v_new_ids, v_result_id);
    v_nums := array_append(v_new_nums, v_num);
    v_dens := array_append(v_new_dens, v_den);
  end loop;

  return array_length(v_ids, 1) = 1 and v_nums[1] = 24 * v_dens[1];
exception
  when others then
    return false;
end;
$$;

create or replace function public.ensure_daily_event(p_event_date date default public.today_in_shanghai())
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event_id uuid;
begin
  insert into public.daily_events (event_date, starts_at, ends_at)
  values (
    p_event_date,
    p_event_date::timestamp at time zone 'Asia/Shanghai',
    (p_event_date + 1)::timestamp at time zone 'Asia/Shanghai'
  )
  on conflict (event_date) do update
  set event_date = excluded.event_date
  returning id into v_event_id;

  if (select count(*) from public.event_puzzles where event_id = v_event_id) < 10 then
    insert into public.event_puzzles (event_id, puzzle_index, puzzle_id)
    select
      v_event_id,
      (row_number() over (order by md5(p_event_date::text || ':' || pb.id::text)))::int,
      pb.id
    from public.puzzle_bank pb
    order by md5(p_event_date::text || ':' || pb.id::text)
    limit 10
    on conflict do nothing;
  end if;

  if (select count(*) from public.event_puzzles where event_id = v_event_id) < 10 then
    raise exception 'Puzzle bank must contain at least 10 puzzles';
  end if;

  return v_event_id;
end;
$$;

create or replace function public.build_run_state(p_run_id uuid)
returns jsonb
language plpgsql
security definer
stable
set search_path = public
as $$
declare
  v_state jsonb;
begin
  select jsonb_build_object(
    'run_id', r.id,
    'event_date', e.event_date,
    'started_at', r.started_at,
    'completed_at', r.completed_at,
    'score_ms', r.score_ms,
    'puzzles', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'puzzle_index', ep.puzzle_index,
          'numbers', to_jsonb(pb.numbers),
          'solved', rs.run_id is not null
        )
        order by ep.puzzle_index
      ),
      '[]'::jsonb
    )
  )
  into v_state
  from public.runs r
  join public.daily_events e on e.id = r.event_id
  join public.event_puzzles ep on ep.event_id = e.id
  join public.puzzle_bank pb on pb.id = ep.puzzle_id
  left join public.run_solutions rs
    on rs.run_id = r.id
   and rs.puzzle_index = ep.puzzle_index
  where r.id = p_run_id
  group by r.id, e.event_date, r.started_at, r.completed_at, r.score_ms;

  return v_state;
end;
$$;

create or replace function public.set_profile(p_nickname text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_nickname text := left(nullif(trim(p_nickname), ''), 24);
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if v_nickname is null then
    raise exception 'Nickname cannot be empty';
  end if;

  insert into public.profiles (id, nickname)
  values (v_user_id, v_nickname)
  on conflict (id) do update
  set nickname = excluded.nickname,
      updated_at = now();

  return jsonb_build_object('id', v_user_id, 'nickname', v_nickname);
end;
$$;

create or replace function public.start_daily_run()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_event_id uuid;
  v_run_id uuid;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  insert into public.profiles (id, nickname)
  values (v_user_id, 'Player ' || left(v_user_id::text, 4))
  on conflict (id) do nothing;

  v_event_id := public.ensure_daily_event(public.today_in_shanghai());

  insert into public.runs (user_id, event_id)
  values (v_user_id, v_event_id)
  on conflict (user_id, event_id) do update
  set event_id = excluded.event_id
  returning id into v_run_id;

  return public.build_run_state(v_run_id);
end;
$$;

create or replace function public.resume_daily_run()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_event_id uuid;
  v_run_id uuid;
begin
  if v_user_id is null then
    return null;
  end if;

  v_event_id := public.ensure_daily_event(public.today_in_shanghai());

  select id
  into v_run_id
  from public.runs
  where user_id = v_user_id
    and event_id = v_event_id
  limit 1;

  if v_run_id is null then
    return null;
  end if;

  return public.build_run_state(v_run_id);
end;
$$;

create or replace function public.submit_solution(
  p_run_id uuid,
  p_puzzle_index int,
  p_steps jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_run public.runs%rowtype;
  v_event_date date;
  v_numbers int[];
  v_solved_count int;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_run
  from public.runs
  where id = p_run_id
    and user_id = v_user_id
  for update;

  if v_run.id is null then
    raise exception 'Run not found';
  end if;

  select event_date
  into v_event_date
  from public.daily_events
  where id = v_run.event_id;

  if v_event_date <> public.today_in_shanghai() then
    raise exception 'Only today event can accept submissions';
  end if;

  if v_run.run_status = 'completed' then
    return public.build_run_state(v_run.id);
  end if;

  select pb.numbers
  into v_numbers
  from public.event_puzzles ep
  join public.puzzle_bank pb on pb.id = ep.puzzle_id
  where ep.event_id = v_run.event_id
    and ep.puzzle_index = p_puzzle_index;

  if v_numbers is null then
    raise exception 'Puzzle not found';
  end if;

  if exists (
    select 1
    from public.run_solutions
    where run_id = v_run.id
      and puzzle_index = p_puzzle_index
  ) then
    return public.build_run_state(v_run.id);
  end if;

  if not public.validate_24_solution(v_numbers, p_steps) then
    raise exception 'Invalid solution';
  end if;

  insert into public.run_solutions (run_id, puzzle_index, steps)
  values (v_run.id, p_puzzle_index, p_steps);

  select count(*)
  into v_solved_count
  from public.run_solutions
  where run_id = v_run.id;

  if v_solved_count >= 10 then
    update public.runs
    set run_status = 'completed',
        completed_at = now(),
        score_ms = greatest(
          0,
          floor(extract(epoch from (now() - started_at)) * 1000)::bigint
        )
    where id = v_run.id
      and run_status <> 'completed';
  end if;

  return public.build_run_state(v_run.id);
end;
$$;

create or replace function public.get_today_leaderboard()
returns table (
  rank_position int,
  nickname text,
  score_ms bigint,
  completed_at timestamptz
)
language sql
security definer
stable
set search_path = public
as $$
  with today_event as (
    select id
    from public.daily_events
    where event_date = public.today_in_shanghai()
  ),
  ranked as (
    select
      (row_number() over (order by r.score_ms asc, r.completed_at asc, r.user_id asc))::int as rank_position,
      coalesce(p.nickname, 'Player') as nickname,
      r.score_ms,
      r.completed_at
    from public.runs r
    left join public.profiles p on p.id = r.user_id
    where r.event_id = (select id from today_event)
      and r.run_status = 'completed'
      and r.score_ms is not null
  )
  select rank_position, nickname, score_ms, completed_at
  from ranked
  order by rank_position
  limit 100;
$$;

create or replace function public.get_history_leaderboard()
returns table (
  rank_position int,
  nickname text,
  total_points bigint,
  completed_days bigint,
  best_score_ms bigint,
  last_completed_at timestamptz
)
language sql
security definer
stable
set search_path = public
as $$
  with event_ranks as (
    select
      r.user_id,
      r.score_ms,
      r.completed_at,
      (row_number() over (
        partition by r.event_id
        order by r.score_ms asc, r.completed_at asc, r.user_id asc
      ))::int as event_rank
    from public.runs r
    where r.run_status = 'completed'
      and r.score_ms is not null
  ),
  scored as (
    select
      user_id,
      case event_rank
        when 1 then 25
        when 2 then 18
        when 3 then 15
        when 4 then 12
        when 5 then 10
        when 6 then 8
        when 7 then 6
        when 8 then 4
        when 9 then 2
        else 1
      end as points,
      score_ms,
      completed_at
    from event_ranks
  ),
  grouped as (
    select
      user_id,
      sum(points)::bigint as total_points,
      count(*)::bigint as completed_days,
      min(score_ms)::bigint as best_score_ms,
      max(completed_at) as last_completed_at
    from scored
    group by user_id
  ),
  ranked as (
    select
      (row_number() over (
        order by
          g.total_points desc,
          g.completed_days desc,
          g.best_score_ms asc,
          g.last_completed_at asc,
          g.user_id asc
      ))::int as rank_position,
      coalesce(p.nickname, 'Player') as nickname,
      g.total_points,
      g.completed_days,
      g.best_score_ms,
      g.last_completed_at
    from grouped g
    left join public.profiles p on p.id = g.user_id
  )
  select rank_position, nickname, total_points, completed_days, best_score_ms, last_completed_at
  from ranked
  order by rank_position
  limit 100;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant select on public.runs, public.run_solutions to authenticated;

revoke all on public.puzzle_bank from anon, authenticated;
revoke all on public.daily_events from anon, authenticated;
revoke all on public.event_puzzles from anon, authenticated;

revoke execute on function public.ensure_daily_event(date) from public;
revoke execute on function public.build_run_state(uuid) from public;

grant execute on function public.set_profile(text) to authenticated;
grant execute on function public.start_daily_run() to authenticated;
grant execute on function public.resume_daily_run() to authenticated;
grant execute on function public.submit_solution(uuid, int, jsonb) to authenticated;
grant execute on function public.get_today_leaderboard() to anon, authenticated;
grant execute on function public.get_history_leaderboard() to anon, authenticated;
